version: '3.8'
services:
  nginx:
    depends_on:
      - api
      - front
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "3050:80"
  api:
    build:
      context: "./backend"
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - './front:/front' 